import { Oswald } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import Footer from '@/components/footer'


const oswald = Oswald({style: 'normal', weight: '400', preload: false, display: 'swap', serif: false})


export const metadata = {
  title: 'Livraria Biblion',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">   
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/public/favicon.ico" type="image/icon" />
        <title>Biblion</title>
      </head>
      <body className={oswald.className}>{children}
        <Header />
        <Footer />
      </body>
    </html>
  )
}
